Fix some minor mongoengine bugs + bump version
Summary:
1) If there was an $or query object id fields had to explicitly cast to
object ids, instead of being automatically casted like other cases. This
was caused by the op staying as "or" forever.
2) Sentry error caused by unicode error instead of a duplicate key
error: https://sentry.infra.wish.com/sentry/merchant-external-api/issues/462/?query=is:unresolved

Test Plan: inprod

Reviewers: jji, tjackson, vitaliy

Differential Revision: https://phab.wish.com/D105654