adds test for falsey primary_key behaviour
This commit adds a test for the incorrect behaviour raised in
 #1352, in which updating a document with a `0` primary_key fails
with:
> OperationError: attempt to update a document not yet saved
despite prior saving.

The issue is almost certainly due to a failure to distinguish
between `None` and other falsey values.